node('master') 
{
    stage('Continuous Download_bank1') 
	{
    git 'https://github.com/sunildevops77/maven.git'
	}
    stage('Continuous Build_bank1') 
	{
    sh label: '', script: 'mvn package'
	}	
}
